### ISSUE TITLE
Allow for input type in custom mutation definition

### ISSUE THREAD

**Issue by travishaby** [aws-amplify/amplify-data#440]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M2 Pro
  Memory: 1.89 GB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn: 1.22.21 - /opt/homebrew/bin/yarn
  npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: 1.2.0
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-auth: 1.1.0
  @aws-amplify/backend-cli: 1.2.1
  @aws-amplify/backend-data: 1.1.0
  @aws-amplify/backend-deployer: 1.0.2
  @aws-amplify/backend-function: 1.3.0
  @aws-amplify/backend-output-schemas: 1.1.0
  @aws-amplify/backend-output-storage: 1.0.2
  @aws-amplify/backend-secret: 1.0.0
  @aws-amplify/backend-storage: 1.0.4
  @aws-amplify/cli-core: 1.1.1
  @aws-amplify/client-config: 1.1.1
  @aws-amplify/deployed-backend-client: 1.1.0
  @aws-amplify/form-generator: 1.0.0
  @aws-amplify/model-generator: 1.0.2
  @aws-amplify/platform-core: 1.0.3
  @aws-amplify/plugin-types: 1.1.0
  @aws-amplify/sandbox: 1.1.1
  @aws-amplify/schema-generator: 1.2.0
  aws-amplify: 6.4.3
  aws-cdk: 2.150.0
  aws-cdk-lib: 2.150.0
  typescript: 5.5.4
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

It doesn't look like the Gen2 data construct provides the ability to declare [an input type](https://graphql.org/graphql-js/mutations-and-input-types/) when creating a mutation.

I have a fairly complex object that I'm trying to pass in to write a record, and an input type that accepted nested input types would be ideal in order to keep the schema DRY and make things clearer.

Thanks!

**Comment by orgtom78** [comment]
@chrisbonifacio any progress on this? Can you confirm that this statement:

> Another use-case that is currently not supported is that of filter input types.
> 
> All auto-generated queries have a filter argument as shown below and it is currently not possible to something similar with custom queries in Gen 2 since we can't define/use input types and nest them.

is indeed correct and that there is currently no way to assign custom filters to an existing e.g. dynamodb? 
If yes, are you still treating this as a feature request or bug? Seems borderline and appreciate any updates on this.

**Comment by stocaaro** [comment]
Hey all,

You can now [use customType's in your query/mutation operation argument](https://docs.amplify.aws/react/build-a-backend/data/custom-business-logic/#step-2---configure-custom-business-logic-handler-code). 

This was released earlier this year and under the hood custom types used in this way generate graphql Inputs corresponding with the expected formats and get transformed to the expected client call types.

re: @jmarshall9120 
> I'm not sure how to even get the auto generated types from the schema:

When I want to inspect the generated schema's I add `console.log(schema.transform());` after my data definition in my `amplify/data/resource.ts` file and this will get output in the sandbox build output before it starts synthesizing the backend.

I think this is resolved, but I'll leave this open in case there are unaddressed threads or issues with the new behavior.

Thanks,
Aaron

**Comment by olegsid** [comment]
> Hey all,
> 
> You can now [use customType's in your query/mutation operation argument](https://docs.amplify.aws/react/build-a-backend/data/custom-business-logic/#step-2---configure-custom-business-logic-handler-code).
> 
> This was released earlier this year and under the hood custom types used in this way generate graphql Inputs corresponding with the expected formats and get transformed to the expected client call types.
> 
> re: [@jmarshall9120](https://github.com/jmarshall9120)
> 
> > I'm not sure how to even get the auto generated types from the schema:
> 
> When I want to inspect the generated schema's I add `console.log(schema.transform());` after my data definition in my `amplify/data/resource.ts` file and this will get output in the sandbox build output before it starts synthesizing the backend.
> 
> I think this is resolved, but I'll leave this open in case there are unaddressed threads or issues with the new behavior.
> 
> Thanks, Aaron

Seems like issue is not resolved becouse it is not possible to pass an array of object as an argument of mutation. it is not possible to add custom type and array as argument

**Comment by stocaaro** [comment]
Hello @olegsid ,

With the latest change you can pass an array of objects as arguments for a mutation by using a named custom type and a ref, which would look like this:

```
const schema = a.schema({
  ConfigType: a.customType({
        filter: a.string(),
        ...
      }),
  
  setConfigs: a
    .mutation()
    .arguments({
      configs: a.ref('ConfigType').array(),
    })
    .returns(a.string())
    .authorization(allow => [allow.authenticated()])
});
```

We are tracking a feature request to be able to use `require` and `array` modifiers directly on an inline custom type and until this work happens the only pattern to define a required or array custom type argument for a mutation is by using `ref`.

Can you confirm that this is working for you when your using the most current version of the library?

Thanks,
Aaron
